id: I4BFF6F1E
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-14 15:22:17.619215+00:00
last_modified: 2022-12-14 15:22:17.619222+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-061-004
  eft-text-version: 1.0.10 2020
  title: Toh_184-Teaching_the_Practice_of_a_Bodhisattva-v2
bases:
  1DE4:
    source_metadata: null
    order: 1
    base_file: 1DE4.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
